### ISSUE TITLE
Lightdm missing display setup script

### ISSUE THREAD

**Issue by hadesagd** [arcolinux/arcolinux-dwm#1]
This is just a heads up. I switched to arcolinux a few weeks ago and as much as I loved it, I was having many issues with my home monitor setup, a laptop and an external monitor. When booting I would get lightdm to display properly on the laptop screen but not on the monitor since the two have different resolutions. I finally found that lightdm.conf did not have the display-setup-script option set. I hardcoded my screen setup with xrandr in lightdm.conf and that solved my issue, however I would suggest creating a script that sets up the screens automatically, for us noobs it would make life a lot easier.

**Comment by anonymous352** [comment]
There are xrandr examples in the ~/.config/arco-dwm/autostart.sh file.
________________________________

**Comment by arcolinuxz** [comment]
easier said then done

**Comment by hadesagd** [comment]
@anonymous352 thank you for your input. I tried uncommenting some of those settings but I was still getting some errors, that forced me to restart the window manager right after boot. I also did not like that lightdm was showing the login on both the laptop monitor and the external monitor, and only setting up the lightdm display-setup-script got the behavior that I wanted.

@arcolinuxz Perhaps my post was not properly written and sounded mean, not my intention. I absolutely love all the work put into Arcolinux and the learning path approach is the best that I have seen in 20+ years of distro hopping. Thank you for your amazing work.

I am no software engineer, but I wrote this script to put in my display-setup-script. This is the first issue that I open in GitHub and I am not familiar on how to contribute, please forgive my lack of etiquette if that is the case.

```bash
#!/bin/bash

# Let's try to get the information from the display and print the entries

# First get the monitor count

monCount=$(xrandr -q | grep "\<connected" | wc -l)

# Get the names of the outputs that are connected and save them to an array
# the names will allow us to build the xrandr commands later

activeMonitors=`xrandr -q | grep "\<connected" | awk '{ print $1 }'`

activeOutputs=()

for monitor in $activeMonitors
do 
    activeOutputs+=($monitor)
done

# Build the case form for multiple Xrandr options
# This will work with up to 4 monitors, the settings will be the preferred output as detected by xrandr
# The primary display will always be the first one detected usually an eDP or LVDS on a laptop, then
# the rest are listed in alphabetical order

case $monCount in
    1)
        xrandr --output ${activeOutputs[0]} --primary --auto;;
    2)
        xrandr --output ${activeOutputs[0]} --primary --auto --output ${activeOutputs[1]} --auto --right-of ${activeOutputs[0]};;
    3)
        xrandr --output ${activeOutputs[0]} --primary -auto --output ${activeOutputs[1]} --auto --right-of ${activeOutputs[0]} --output ${activeOutputs[2]} --auto --right-of ${activeOutputs[1]};;
    4)
        xrandr --output ${activeOutputs[0]} --primary -auto --output ${activeOutputs[1]} --auto --right-of ${activeOutputs[0]} --output ${activeOutputs[2]} --auto --right-of ${activeOutputs[1]} --output ${activeOutputs[3]} --auto --right-of ${activeOutputs[2]};;
    *)
        # More than four monitors leave a message in .xsession-errors
        echo "More than 4 monitors in your setup, need to fix that manually with xrandr or arandr" >> $(HOME)/.xsession-errors;;
esac
```
